/* Chest-port case_steps in the data-driven `outcomes` schema (engine v2).
   Source of truth mirrored to the DB (db/seed_chestport_steps.sql). Reproduces the
   former hardcoded STEP tree exactly so the existing suites keep passing.
   Node require() for tests; the real game reads the same shape from the DB. */
module.exports = [
  { n: 1, title: "Time-out & positioning", node: "rij_access", best: "timeout",
    prompt: "Pre-procedure. How do you begin?",
    outcomes: {
      timeout: { label: "Time-out + US survey of the right IJ", note: "Correct — confirm patency/compressibility",
        score: [{ cat: "technical", delta: 0, reason: "Time-out and US survey performed." }],
        ok: "Site confirmed; right IJ patent and compressible." },
      skip: { label: "Skip the time-out, patient's waiting", note: "Guideline violation",
        score: [{ cat: "technical", delta: -3, reason: "Skipped surgical time-out.", cite: "Universal Protocol" }],
        ok: "You proceed without a time-out." },
    },
    default: { score: [{ cat: "technical", delta: -3, reason: "Off-protocol before a time-out." }], narrative: "You do something else before the time-out." } },

  { n: 2, title: "Venous access", node: "rij_access", best: "us",
    prompt: "Obtain venous access and secure a working wire to the SVC/IVC.",
    outcomes: {
      us: { label: "US-guided micropuncture (21G), 0.018 → exchange → 0.035 Bentson", note: "Correct, lowest pneumothorax risk",
        needs: ["micropuncture-needle-21g", "mp-wire-018", "transitional-dilator-5f", "bentson-035-145"], imaging: "tap",
        complication: { name: "Pneumothorax", mult: 1.0, decline: { sbpDrop: 4, spo2Drop: 4, rrRise: 6 } },
        ok: "Clean US-guided access; 0.035 wire seated in the SVC.", hit: "Access obtained, but the post-access check shows a pneumothorax." },
      us_glide: { label: "US-guided micropuncture, exchange to 0.035 hydrophilic wire", note: "Equivalent safe technique — hydrophilic tracks easier (MODELED)",
        needs: ["micropuncture-needle-21g", "mp-wire-018", "transitional-dilator-5f", "glidewire-035-150"], ownedOnly: true, imaging: "tap",
        score: [{ cat: "technical", delta: 0, reason: "US-guided access; exchanged to a hydrophilic working wire (lubricity 9, MODELED)." }],
        complication: { name: "Pneumothorax", mult: 1.0, decline: { sbpDrop: 4, spo2Drop: 4, rrRise: 6 } },
        ok: "Clean US-guided access; hydrophilic wire glides to the SVC.", hit: "Access obtained, but the post-access check shows a pneumothorax." },
      landmark: { label: "Landmark stick (faster, no US)", note: "Higher pneumothorax risk",
        needs: ["micropuncture-needle-21g", "bentson-035-145"], imaging: "tap",
        score: [{ cat: "technical", delta: -3, reason: "Landmark venipuncture instead of real-time US guidance.", cite: "US guidance is standard of care [1]" }],
        complication: { name: "Pneumothorax", mult: 5.0, decline: { sbpDrop: 4, spo2Drop: 4, rrRise: 6 } },
        ok: "Landmark access happened to work this time.", hit: "Blind stick — the patient desaturates; pneumothorax." },
    },
    default: { score: [{ cat: "technical", delta: -4, reason: "That maneuver does not establish venous access." }], narrative: "That doesn't get you access." } },

  { n: 3, title: "Create the pocket", node: "rij_access", best: "pocket",
    prompt: "Create the subcutaneous pocket on the pectoralis fascia.",
    outcomes: {
      pocket: { label: "Anesthetize, incise, develop a snug pocket", note: "Coag-dependent",
        complication: { name: "Pocket hematoma", multFrom: "platelets", mult: 1.0, multLow: 3.0, multVeryLow: 8.0, decline: { sbpDrop: 6 } },
        ok: "Pocket created with good hemostasis.", hit: "Oozing in the pocket — a hematoma is developing." },
      transfuse: { label: "Order platelet transfusion first, then pocket", note: "Only meaningful if platelets are low", transfuse: true },
    },
    default: { score: [{ cat: "technical", delta: -3, reason: "Off-protocol at pocket creation." }], narrative: "That isn't how you create the pocket." } },

  { n: 4, title: "Tunnel & measure", node: "right_bct", best: "measure",
    prompt: "Tunnel the catheter and set tip length to the cavoatrial junction.",
    outcomes: {
      measure: { label: "Measure against the wire under fluoro, trim to CAJ", note: "Correct",
        needs: ["port-catheter-8f"], imaging: "tap",
        score: [{ cat: "technical", delta: 0, reason: "Tip length measured to the CAJ under fluoroscopy." }],
        ok: "Catheter trimmed so the tip will sit at the CAJ." },
      estimate: { label: "Eyeball the length to save fluoro", note: "Malposition risk",
        needs: ["port-catheter-8f"], imaging: "reposition", setFlag: "malposition",
        score: [{ cat: "technical", delta: -4, reason: "Estimated catheter length instead of fluoroscopic measurement — tip malposition." }],
        ok: "Estimated length; the tip looks high — you'll need to reposition later." },
    },
    default: { score: [{ cat: "technical", delta: -3, reason: "Off-protocol at tunneling." }], narrative: "That isn't the tunneling/measuring step." } },

  { n: 5, title: "Sheath & catheter delivery", node: "svc", best: "valsalva_gentle",
    prompt: "Deliver the catheter through the peel-away sheath to the CAJ.",
    outcomes: {
      valsalva_gentle: { label: "Valsalva/breath-hold, pinch sheath, gentle advance", note: "Correct technique",
        needs: ["peelaway-sheath-9f"], ok: "Sheath placed with air-embolism precautions; catheter advanced gently (resistance LOW). Tip at the CAJ." },
      no_breathhold: { label: "Advance briskly without a breath-hold", note: "Air-embolism risk",
        needs: ["peelaway-sheath-9f"],
        modeledEvent: { name: "Air embolism", decline: { sbpDrop: 18, spo2Drop: 6, rrRise: 4 }, note: "Open sheath without breath-hold entrained air (procedure step 5 precaution)." },
        hit: "As the dilator comes out you hear a gasp — air embolism." },
      forceful: { label: "Seat it deep with a firm forceful push", note: "Watch tactile resistance",
        needs: ["peelaway-sheath-9f"],
        stress: { device: "port-catheter-8f", node: "caj", force: "forceful", critScore: -4, riskPct: 40,
          event: { name: "CAJ perforation → pericardial effusion", decline: { sbpDrop: 30, spo2Drop: 2, rrRise: 4 }, note: "Over-forceful advance at the fragile cavoatrial junction against critical resistance." },
          hit: "Sudden give, then hypotension — you've perforated the CAJ.",
          critOk: "It seats deep — resistance was CRITICAL but it held this time. Don't push against that." },
        ok: "It seats deep; resistance was high but held." },
    },
    default: { score: [{ cat: "technical", delta: -3, reason: "Off-protocol at catheter delivery." }], narrative: "That isn't the delivery step." } },

  { n: 6, title: "Connect & test", node: "caj", best: "aspirate",
    prompt: "Connect the port and test it.",
    outcomes: {
      aspirate: { label: "Lock to stem; Huber access; aspirate + flush each lumen", note: "Correct",
        needs: ["huber-needle-20g"], score: [{ cat: "technical", delta: 0, reason: "Brisk blood return and free flush confirmed." }],
        ok: "Brisk blood return, free flush, no pocket swelling." },
      skip: { label: "Skip the aspiration test, it looked fine", note: "Guideline violation",
        score: [{ cat: "technical", delta: -3, reason: "Skipped the aspiration/flush patency test." }], ok: "You skip the patency check." },
    },
    default: { score: [{ cat: "technical", delta: -3, reason: "Off-protocol at port testing." }], narrative: "That isn't the connect/test step." } },

  { n: 7, title: "Confirm tip & close", node: "caj", best: "dsa",
    prompt: "Confirm final tip position and close.",
    outcomes: {
      dsa: { label: "DSA spot to document CAJ tip, then two-layer close", note: "Correct",
        imaging: "dsa", contrastMl: 3, ifFlag: "malposition",
        ifFlagScore: [{ cat: "technical", delta: -3, reason: "Malpositioned tip required repositioning before closure." }], ifFlagImaging: "reposition",
        ifFlagNarrative: "Spot shows the tip was high; repositioned to the CAJ, then closed.",
        elseScore: [{ cat: "technical", delta: 0, reason: "Fluoroscopic spot documents CAJ tip without kinks." }],
        elseNarrative: "Tip confirmed at the CAJ; pocket closed in two layers." },
      noconfirm: { label: "Close without a confirmatory image", note: "Misses malposition",
        score: [{ cat: "technical", delta: -6, reason: "Closed without documenting final tip position." }],
        ifFlag: "malposition", ifFlagScore: [{ cat: "safety", delta: 0, reason: "Undocumented malpositioned tip left in place." }],
        narrative: "You close without a confirmatory spot film." },
    },
    default: { score: [{ cat: "technical", delta: -4, reason: "Off-protocol at closure." }], narrative: "That isn't the confirm/close step." } },
];
